### ISSUE TITLE
Version php7.2

### ISSUE THREAD

**Issue by Darkbelg** [dakzilla/magento2-intervention-image-helper#4]
I noticed that the latest version is php constrained to ~7.0.0. But i also see that the dev-master does not have these constraints. Is the dev-master ok to use in production? And are there any plans to release another version with the php constraint ?

**Comment by dakzilla** [comment]
Hey @Darkbelg, the master branch is not functional as far as I know. I did something stupid in the constructor of the Image class at some point. Tag 1.0.5 is the latest functional version and is also the one that is available from Packagist.

I'll try to have a look at it when I can, but since I no longer work with Magento, it will take time to bring my local setup back up. A pull request would be appreciated if you can!

**Comment by dakzilla** [comment]
Hey @Darkbelg,

I've pushed tag 1.0.6 with the PHP version constraint removed. I also tested the package on Magento 2.3, where I found no issues.

Commit: 8d663d1369286009de7024055055d734f241b1f0

Thanks!

**Comment by Darkbelg** [comment]
Hello @dakzilla 

Thank you for the quick response. Do you recommend to keep using this module. Or should we look for alternatives ?

**Comment by dakzilla** [comment]
Hi @Darkbelg,

I've just tested this module on Magento 2.3 and it works correctly. I know of a web agency in Montreal that has used it in all of its M2 projects for years. I think it's a good module and you should give it a try :) 

As an alternative, if you only need to resize images, you can have a look at https://github.com/staempfli/magento2-module-image-resizer

**Comment by Darkbelg** [comment]
I know it's a good module we also use it in our shops. It's just that you said you no longer work on magento projects. So i don't know how long you will keep up support for this module if something breaks. That's why i'm asking if we should look for alternatives to use in new projects.

**Comment by dakzilla** [comment]
You're welcome to submit a PR if something breaks :)
